### ISSUE TITLE
Long text overflows in cards

### ISSUE THREAD

**Issue by kjgr** [cse110-fa22-group25/warrantracker#51]

**Comment by kjgr** [comment]
Hey. The solution in the styling branch does not behave properly when resizing. I implemented a CSS fix for overflow in a new branch (handling-overflow-in-cards) which works well.

**Comment by chrisliang12** [comment]
> Hey. The solution in the styling branch does not behave properly when resizing. I implemented a CSS fix for overflow in a new branch (handling-overflow-in-cards) which works well.

can you mention in what situation the overflow still exists?

**Comment by kjgr** [comment]
There is no overflow when using javascript. However, When you resize the window horizontally, the title gets into two lines and second line ends with dots.  Using CSS keeps it at one line and reduces number of visible characters while adding the dots. I think that looks good ?

**Comment by chrisliang12** [comment]
Got it. I think your solution is better. I will change the styling branch and use your code.

**Comment by kjgr** [comment]
I implemented the overflow fix with the current styling branch. I copied the style we were going for.

**Comment by chrisliang12** [comment]
> I implemented the overflow fix with the current styling branch. I copied the style we were going for.

You can contribute to the styling branch directly. no need to copy the whole styling stuff.

**Comment by chrisliang12** [comment]
I think it should be easier if you edit on top of the styling branch. Currently, the create_card method in your branch is the old version.
